package ru.gavarent.lighthouse.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006398)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcbe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF161c22)
val md_theme_light_secondary = Color(0xFF7f5700)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdea9)
val md_theme_light_onSecondaryContainer = Color(0xFF281800)
val md_theme_light_tertiary = Color(0xFF006494)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc8e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e31)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a17)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a17)
val md_theme_light_surfaceVariant = Color(0xFFdee3ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72777e)
val md_theme_light_inverseOnSurface = Color(0xFFfaeee8)
val md_theme_light_inverseSurface = Color(0xFF352f2b)

val md_theme_dark_primary = Color(0xFF90ccff)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004b75)
val md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
val md_theme_dark_secondary = Color(0xFFfabb49)
val md_theme_dark_onSecondary = Color(0xFF442c00)
val md_theme_dark_secondaryContainer = Color(0xFF604100)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdea9)
val md_theme_dark_tertiary = Color(0xFF8bceff)
val md_theme_dark_onTertiary = Color(0xFF003450)
val md_theme_dark_tertiaryContainer = Color(0xFF004b71)
val md_theme_dark_onTertiaryContainer = Color(0xFFc8e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a17)
val md_theme_dark_onBackground = Color(0xFFece0da)
val md_theme_dark_surface = Color(0xFF201a17)
val md_theme_dark_onSurface = Color(0xFFece0da)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8c9198)
val md_theme_dark_inverseOnSurface = Color(0xFF201a17)
val md_theme_dark_inverseSurface = Color(0xFFece0da)

val seed = Color(0xFF3d5a73)
val error = Color(0xFFba1b1b)